stages:
  - lint
  - build

linting:
  stage: lint
  image: golang:1.14
  cache:
    key: go-dependencies
    paths:
      - .cache
  before_script:
    - mkdir -p .cache
    - export GOPATH="$CI_PROJECT_DIR/.cache"
    - export PATH=$PATH:$GOPATH/bin
    - go get -u golang.org/x/lint/golint
    - go get -v -d ./...
  script:
    - golint -set_exit_status $(go list ./...)
    - go vet $(go list ./...)

building:
  stage: build
  image: golang:1.14
  cache:
    key: go-dependencies
    paths:
      - .cache
  before_script:
    - mkdir -p .cache
    - mkdir -p bin
    - export GOPATH="$CI_PROJECT_DIR/.cache"
  script:
    - make
  artifacts:
    name: bot
    expose_as: bot
    paths:
      - bin/bot

