---
development:
  dialect: "sqlite3"
  database: buffalo_coke_buffalo_coke_development.sqlite

test:
  dialect: "sqlite3"
  database: buffalo_coke_buffalo_coke_test.sqlite

production:
  dialect: "sqlite3"
  database: buffalo_coke_buffalo_coke_production.sqlite
